name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: martinloesethjensen/gh-workflows/.github/workflows/build-ipa.yml@main
    with:
      scheme_name: GenkiFlow
      bundle_id: dev.martinloeseth.GenkiFlow
      app_name: GenkiFlow
      # min_os_version: "16.0"   # optional, defaults to 16.0
    secrets:
      ALTSTORE_SOURCE_PAT: ${{ secrets.ALTSTORE_SOURCE_PAT }}
